### ISSUE TITLE
Refresh after opening notifications in browser (after a delay)

### ISSUE THREAD

**Issue by yzhang-gh** [fabiospampinato/vscode-github-notifications-bell#1]
Another nice extension from you 🤣

After I view the notifications in the browser, the status bar item remains unchanged. I would suggest refreshing in a minute after "open in browser" command.

**Comment by fabiospampinato** [comment]
> Another nice extension from you 🤣

What can I say, I have a lot of time on my hands 😂 

> After I view the notifications in the browser, the status bar item remains unchanged. I would suggest refreshing in a minute after "open in browser" command.

Yes the state should be updated rapidly after opening the notifications. I thought about this but since I don't think there's a way of detecting when you viewed all the notifications, or simply closed the tab, I haven't implemented it yet.

Refreshing it after a minute, or a configurable amount, could be a good enough solution. I'll think about it 👍

**Comment by fabiospampinato** [comment]
Maybe I could detect when VSC regains the focus, which often will be when you closed the notifications tab 🤔 But I'm not sure they are exposing APIs for detecting this.

**Comment by yzhang-gh** [comment]
> Maybe I could detect when VSC regains the focus, which often will be when you closed the notifications tab 🤔 But I'm not sure they are exposing APIs for detecting this.

Electron provides such an API, but VSC seems not.

**Comment by fabiospampinato** [comment]
Maybe let's wait on [this](https://github.com/Microsoft/vscode/issues/18263) to be implement first.

Unless we can think of another, possibly cross-platform, way of detecting this.

Waiting 1 minute or whatever seems a bit rough.

**Comment by yzhang-gh** [comment]
Upvoted. Although it seems to need forever to get implemented 😂

**Comment by yzhang-gh** [comment]
I'm wrong. It looks already implemented. Microsoft/vscode#31130.

**Comment by fabiospampinato** [comment]
Nice, feel free to make a PR for that ;)

I think it should work like this:

- After opening the notifications page we should use `setInterval` and check every 1s or something if the window is focused
- Once it's focused again force a refresh and clear the interval
