### ISSUE TITLE
Number of notifs out of sync

### ISSUE THREAD

**Issue by bartocc** [fabiospampinato/vscode-github-notifications-bell#13]
I might be doing something wrong, but the extension tells me I have 50 notifs while I have none in `https://github.com/notifications`.

Nothing changes after doing a `GitHub Notifications: Refresh`.

**Comment by fabiospampinato** [comment]
There seems to have been a GitHub outage, maybe that was the issue. Or perhaps the extension hit the API limits and isn't able to refresh its state. I can't think of another possible cause 🤔 

Let's track this here: https://github.com/fabiospampinato/vscode-github-notifications-bell/issues/10

Let me know if the issue persists in the next days.
