### ISSUE TITLE
The token is not pulling notifications. It says "never used"

### ISSUE THREAD

**Issue by mariela21180** [fabiospampinato/vscode-github-notifications-bell#14]
Even though I've created the token and set it on the Sertings, it's not working and the notifications are not dispayed.

The token says this: 
![image](https://user-images.githubusercontent.com/3533830/65180890-45759880-da34-11e9-84f5-c781f81983e5.png)

I have it on the config and says 0 notifications:

```[[redacted-token]]```

Even though I have notifications on github:
![image](https://user-images.githubusercontent.com/3533830/65180962-6807b180-da34-11e9-9090-aec3ab7540fb.png)

**Comment by fabiospampinato** [comment]
I've redacted your post to remove the screenshot containing your personal token, but I've just realized that one can view the full edits history anyway, so you should probably revoke it that create a new one.

I'm not sure why the extension seems to not be working for you, what happens if you run `GitHub Notifications: Refresh`?

**Comment by Logerfo** [comment]
@fabiospampinato you should be able to remove the revision from the history

**Comment by mariela21180** [comment]
> I've redacted your post to remove the screenshot containing your personal token, but I've just realized that one can view the full edits history anyway, so you should probably revoke it that create a new one.
> 
> I'm not sure why the extension seems to not be working for you, what happens if you run `GitHub Notifications: Refresh`?


@fabiospampinato 

Thanks for let me know about the token edit.

I've run the command you suggest.

It says this: 
![image](https://user-images.githubusercontent.com/3533830/65352716-ab435b00-dbc1-11e9-9c99-ece8b8fbd5c1.png)

But I've never had any notifications number on the icon since I've configured it, although that I have had notifications on Github

**Comment by mariela21180** [comment]
This is the version I have installed in case it helps:

![image](https://user-images.githubusercontent.com/3533830/65353246-09bd0900-dbc3-11e9-8cb7-d48a9c201c7f.png)

**Comment by fabiospampinato** [comment]
@Logerfo Oh cool I didn't know about that, thanks!

> It says this:

It seemed to be working and you just had 0 notifications.

> But I've never had any notifications number on the icon since I've configured it, although that I have had notifications on Github

It doesn't update immediately, and if you hit your API limits (if it makes too many requests) it doesn't update at all, maybe that's the issue?

**Comment by fabiospampinato** [comment]
v2.3.1 should fix this 👍

**Comment by mariela21180** [comment]
> v2.3.1 should fix this 👍

It's working now with the update! Thanks!

![image](https://user-images.githubusercontent.com/3533830/65462618-8f8fbd00-de2c-11e9-9c19-0971f35a1bd2.png)
