### ISSUE TITLE
icons not displaying

### ISSUE THREAD

**Issue by steveoh** [fabiospampinato/vscode-github-notifications-bell#17]
I get an icon if i use the `mark-github` but if i use something like `octicon-zap` [link](https://octicons.github.com/icon/zap/) or something it disappears. Also the color does not appear to update.

As for the color I entered #f012be is this the right format?

**Comment by fabiospampinato** [comment]
I believe the color is only used when you have some notification you participated in.

I guess `octicon-zap` isn't supported by VSCode, they recently updated all their icons and kind of diverged from what octicons is providing, the available icons should be listed [here](https://github.com/microsoft/vscode-codicons/tree/master/src/icons).

**Comment by fabiospampinato** [comment]
> I believe the color is only used when you have some notification you participated in.

Or maybe not, have you tried restarting the app?

**Comment by steveoh** [comment]
Ok, the color thing is correct. Doesn't change until there is a notification. Adding a sample color to the repo somewhere would be helpful so I know i'm doing it right. 

And then the [docs](https://github.com/fabiospampinato/vscode-github-notifications-bell/blob/master/README.md#L53) should be updated to not reference the `octicon-` any longer. Thanks for the new link.

Great extension idea by the way 🚀

**Comment by fabiospampinato** [comment]
> Adding a sample color to the repo somewhere would be helpful so I know i'm doing it right.

Probably, but you also at the end of the day wrote it correctly. It should be clearer that it only applies when there are some notifications.

> And then the docs  should be updated to not reference the octicon- any longer. Thanks for the new link.

Yes, but I would have to update a few of my extensions because of this and I currently don't have the time to do that, if anybody wants to help PRs are welcome 👍
