### ISSUE TITLE
UI enhancements

### ISSUE THREAD

**Issue by yzhang-gh** [fabiospampinato/vscode-github-notifications-bell#2]
It might be better to

1. make use of the theme foreground colour for status bar item
   ![image](https://user-images.githubusercontent.com/7588612/47374824-c7efbe00-d6e6-11e8-9f74-27766bbab01a.png)
2. mimic vscode notification center (adding notification number)
   ![image](https://user-images.githubusercontent.com/7588612/47374966-1bfaa280-d6e7-11e8-9b58-df378c031ea9.png)

**Comment by fabiospampinato** [comment]
> make use of the theme foreground colour for status bar item

This is a bit tricky. First of all there are already settings for changing all the colors.

Now, that statusbar item has 3 states: `no notifications`, `some notifications` and `some notifications and participating`. I assume in your screenshot it's in the `no notifications` state. 

I could change this color to be the default one, then the `some notifications` color might be white and `participating` might still be yellow. This would work better in your theme, but not in other themes where by default the color is white. In that situation it would be impossible to distinguish, without manually setting the colors, between `no notifications` and `some notifications`.

Until they implement [this](https://github.com/Microsoft/vscode/issues/32813) I can't provide good defaults for everyone.

> mimic vscode notification center (adding notification number)

The notification center is always displayed, so they need to show the counter to notify that there are some notifications. This extension uses color for that instead. Also you can hide the icon if there are no notifications.

You can already hover over the icon and get the counters.

Adding a setting or something for writing those counters to the statusbar would be nice though, thanks for the suggestion 👍

**Comment by yzhang-gh** [comment]
It occurred to me that there might be two schemes.

The first one is the current solution, using different colours to indicate 3 different states.
The other one is what VSC does, no different colours but it shows the number of messages.

In the second setting, we can always reference `statusBar.foreground` theme key.

**Comment by yzhang-gh** [comment]
BTW, why bother distinguishing `some notifications` and `some notifications and participating`? Both ends up with opening in the browser (at least for me😂)

**Comment by fabiospampinato** [comment]
Originally I thought that notifications about things I'm actually participating in would be more important to me, but at the end of the day I'm just keep viewing both of them. In hindsight it probably just over-complicated things. 

I'm currently working on other stuff, and these changes aren't really necessary for me, but if you want to make the changes yourself I'll be happy to consider a PR that:

- Removes the extra `some notifications and participating` state
- Uses the default color when there are no notifications and a custom, settable, color when there are some
- Adds an option for displaying the number of notifications alongside the icon
