### ISSUE TITLE
Incorrect designation of the GitHub access token

### ISSUE THREAD

**Issue by ferenczy** [fabiospampinato/vscode-github-notifications-bell#20]
Just a minor naming issue: you're designating the GitHub access token as "OAuth" everywhere - on the extension page, extension's settings, notifications, etc. But it's actually the *PAT (Personal Access Token)*, as you can see on GitHub when creating one using the [link](https://github.com/settings/tokens) on your extension's page:

![GitHub's Personal Access Token management](https://user-images.githubusercontent.com/1712992/117172806-6f77fc00-adcc-11eb-920d-9e74031e26e8.png)

**Comment by fabiospampinato** [comment]
Fixed in v3.
