### ISSUE TITLE
Error popup despite correct setup

### ISSUE THREAD

**Issue by mediafinger** [fabiospampinato/vscode-github-notifications-bell#21]
Thx for this extension, it's really handy :octocat: 

---

The error message:

```
You need to provide an OAuth token either via the "githubNotificationsBell.oauthToken" setting  
or the "GITHUB_NOTIFICATIONS_TOKEN" environment variable
```

keeps popping up all the time, despite:

* having `"githubNotificationsBell.oauthToken": "...secret...",` in the Settings
* receiving GitHub notifications as you can see in the screenshot

![Screenshot 2021-05-11 at 13 37 45](https://user-images.githubusercontent.com/457782/117809977-1e9a5480-b25f-11eb-8f1e-0a8170128480.png)

---

Ok, after disabling, reloading and enabling the extension the issue seems to be gone.  
I've done this before though and the error persisted.

So, _no issue anymore for me_. But maybe you can find the reason for this buggy behavior in the code.

**Comment by fabiospampinato** [comment]
It sounds like an issue with vscode maybe, I'm not sure how it could be a problem with the extension itself.
