### ISSUE TITLE
`Open in browser` command does nothing

### ISSUE THREAD

**Issue by yzhang-gh** [fabiospampinato/vscode-github-notifications-bell#5]
Nothing happens when clicking on the status bar item or executing "open in browser" within the vscode command palette.

**Comment by fabiospampinato** [comment]
It is working for me 🤷‍♂️ 

It's strange that you can see the statusbar item but the command isn't working 🤔 What version of VSC are you running?

**Comment by yzhang-gh** [comment]
**VSCode**
Version: 1.29.0-insider (user setup)
Commit: bdfe4fd41f6a5fe538197b3cba937230249a563a
Date: 2018-11-04T13:04:20.759Z
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64

**Windows** 10 Home Insider Preview, build 18272

And I cannot find an error message anywhere. Really strange.

I am going to check whether `open('url')` works in the node repl.

**Comment by yzhang-gh** [comment]
I guess it might be the new Windows Insider build to blame.

Executing `start "https://github.com/notifications"`
- in `cmd` starts another cmd window
- in `powershell` opens the browser

**Comment by fabiospampinato** [comment]
> I guess it might be the new Windows Insider build to blame.

It was working before though, right?

If it wasn't maybe we can switch from [open](https://www.npmjs.com/package/open) to [opn](https://www.npmjs.com/package/opn), which is still maintained. 🤔

**Comment by yzhang-gh** [comment]
Wow, I didn't expect the last `open` update is 5 years ago 😂. I think it is better to adopt `opn`.

Although it might still not be able to solve this issue

> Uses the command `open` on macOS, `start` on Windows and `xdg-open` on other platforms.

---

I tried and there is no luck.

```
> opn('https://github.com/');
Promise {
  <pending>,
  domain:
   Domain {
     domain: null,
     _events: { error: [Function: debugDomainError] },
     _eventsCount: 1,
     _maxListeners: undefined,
     members: [] } }
> (node:16204) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 5): Error: Exited with code 1
```

**Comment by fabiospampinato** [comment]
Maybe they messed up in this Windows update if this was previously working 🤷‍♂️  

Ps. You'll be so much better off with less Windows in your life ;)

**Comment by yzhang-gh** [comment]
😂

**Comment by yzhang-gh** [comment]
Alright, I find an elegant solution `vscode.commands.executeCommand('vscode.open', 'https://...')`

see <https://code.visualstudio.com/docs/extensionAPI/vscode-api-commands>

![image](https://user-images.githubusercontent.com/7588612/48009243-3125f700-e113-11e8-86a9-99731ddb46d1.png)

dependencies -1

**Comment by fabiospampinato** [comment]
But is this something that was working before the latest Windows update? This isn't clear to me.

**Comment by yzhang-gh** [comment]
Yes, it worked. Otherwise, why did I contribute to this extension 😂

**Comment by fabiospampinato** [comment]
Maybe the counter was working but you didn't try to actually open the notifications page or whatever.

I'm a bit conflicted about this, on one hand I hate to change my code just to make it work on Windows, but I do it anyway. This time though they broke something with an update, and I would dislike it even more if this temporary fix would become unnecessary when the next update comes out.

On the other hand I don't want to leave you with a broken extension or force you to fork it.

So I guess feel free to submit a PR where we switch from `open` to `vscode.open`, or wait for the next Windows update to come out.

**Comment by yzhang-gh** [comment]
It is not all about fixing this issue. It would be better, only in my opinion, to depend on `vscode` than to depend on external node module `open` or `opn`. And since VSCode provides such an API, they will be taking care of it, in all platforms, not only for Windows.

It occurred to me today when working on my tex file with the [LaTeX extension](https://marketplace.visualstudio.com/items?itemName=James-Yu.latex-workshop) for VSCode. It can open rendered PDF in the browser. Then I found this solution. (code [here](https://github.com/James-Yu/LaTeX-Workshop/blob/0566b0e0f3465c28c2a64aded8ec6199deb4fb6b/src/components/viewer.ts#L72))

I will create a PR and also, I hope to convince you that, it is _not_ a workaround for a certain version of Windows _but_ a better "dependency" 😂

**Comment by fabiospampinato** [comment]
> I will create a PR and also, I hope to convince you that, it is not a workaround for a certain version of Windows but a better "dependency" 😂

I actually sort of a agree with this. I only have 2 very minor problems with this:

1. I want to solve the same problem in the same way, every time. This today means using `open` in all my extensions. If I'll switch to `vscode.open` here there'll be a voice in the back of my head pushing me to waste time removing `open` from all my other extensions too.
2. The more the code is decoupled from VSC the better. For instance in the near future I'm going to extract `bump-cli` out of my [Bump](https://github.com/fabiospampinato/vscode-bump) extension, and the less its code relies on VSC the better.

**Comment by yzhang-gh** [comment]
> there'll be a voice in the back of my head pushing me to waste time removing `open` from all my other extensions too

So vividly...

> The more the code is decoupled from VSC the better ...

For this little "opening url" task, let's forget about it

😅

**Comment by fabiospampinato** [comment]
It's ok really, I can keep the voices down 😂and I don't plan on making a `github-notifications-cli`, not that eventually replacing `vscode.open` with `open` will be a meaniful problem anyway.

**Comment by yzhang-gh** [comment]
Well, I find a reason for not replacing `open` with `vscode.open` now. `vscode.open` has no configurable options for url (always starts with the default browser). So it is not a good substitution of `open`.

Then, would you mind me removing the target browser option in this extension?

**Comment by fabiospampinato** [comment]
🤔 is it possible to detect when `open` is not working? maybe it throws an error or something? If so I would prefer to use `open` by default and `vscode-open` as a fallback, if it's not easily doable I'm ok with removing the `githubNotificationsBell.openInBrowser` option.

**Comment by yzhang-gh** [comment]
I guess it is not easy since it fails silently (we don't get any error). Let's remove it and see whether `vscode.open` works well for all platforms.

As a core user, I can feel `githubNotificationsBell.openInBrowser` is not a killer feature 😁

**Comment by fabiospampinato** [comment]
Yeah I'm not using it myself either. I'm not quite sure why I added it 🤔

**Comment by yzhang-gh** [comment]
Verified
