### ISSUE TITLE
Would be great to support ENV vars for token

### ISSUE THREAD

**Issue by vfonic** [fabiospampinato/vscode-github-notifications-bell#8]
I use [Settings Sync](https://marketplace.visualstudio.com/items?itemName=Shan.code-settings-sync) VS Code extension to have my settings backed up in secret (not private) gist. Secret gist means gist is only accessible via direct url. It's not private. Private gists don't exist.

I don't want to have my github token (even just for notifications) available on the link that's publicly accessible.

Is there any way to configure github token through ENV vars or global configuration?

**Comment by fabiospampinato** [comment]
Not currently, PR welcome to add support for a "GITHUB_TOKEN" (or "GITHUB_NOTIFICATIONS_TOKEN") env variable 👍
